#!/bin/sh
# Lay the release bundle out and tar it:
#
#   ide-<version>-x86_64-linux/
#     ide            the launcher (bin/ide)
#     main.code      generated by euglena (run `euglena test` first)
#     src/           the genes
#     *.so           the organelles `euglena install` fetched, beside main.code
#     VERSION, README.md
#
#   tools/package.sh <version> <out-dir>
set -eu
version=$1
out=$2
root=$(cd "$(dirname "$0")/.." && pwd)
[ -f "$root/main.code" ] || { echo "no main.code — run euglena test first" >&2; exit 1; }
name="ide-$version-x86_64-linux"
stage="$out/$name"
rm -rf "$stage"
mkdir -p "$stage/src"
cp "$root/bin/ide" "$stage/ide"
cp "$root/main.code" "$root/README.md" "$stage/"
cp "$root"/src/*.gene.code "$stage/src/"
for m in env fs strings syntax tty; do
  so=$(find "$root/.code/modules/$m" -name "$m-linux-x86_64.so" | head -1)
  [ -n "$so" ] || { echo "organelle $m is not installed — run euglena install" >&2; exit 1; }
  cp "$so" "$stage/$m.so"
done
echo "$version" > "$stage/VERSION"
tar -C "$out" -czf "$out/$name.tar.gz" "$name"
echo "$out/$name.tar.gz"
